flask_app/models.py
from flask_app import db

#크롤링한 csv import하는 빈 테이블 생성
class Product(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    product_name = db.Column(db.Text, nullable=True)
    page_url = db.Column(db.Text, nullable=True)
    image_url = db.Column(db.Text, nullable=True)
    price = db.Column(db.Integer, nullable=True)
    clean_name = db.Column(db.Text, nullable=True)

class Search(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    search_name = db.Column(db.String(200), nullable=True)
    created_time = db.Column(db.DateTime, server_default=db.func.now())

flask_app/forms.py
from flask_wtf import FlaskForm

from wtforms import StringField, PasswordField
from wtforms.validators import DataRequired, EqualTo

class ProductForm(FlaskForm):
     product_name = StringField("상품명", validators=[DataRequired()])

flask_app/__init__.py
from . import config
from flask import Flask
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy
from flask import render_template

"""db객체를 create_app함수 안에서 생성하면 블루프린트와 같은 다른 모듈에서 불러올 수 없어서 
db, migrate와 같은 객체를 creat_app 함수 밖에서 생성하고
실제 객체 초기화는 create_app함수에서 init_app함수를 통해 진행"""
db = SQLAlchemy() 
migrate = Migrate()
# 
def create_app():
    app = Flask(__name__)
    app.config.from_object(config) # config.py파일에 작성한 항목을 app.config 환경 변수로 부르기 위해 추가한 코드


    # #ORM 
    db.init_app(app)
    migrate.init_app(app, db) 
    from flask_app import models

    #블루프린트
    from .views import index_view, predict_view
    app.register_blueprint(index_view.bp)
    app.register_blueprint(predict_view.bp)

    return app


if __name__ == '__main__' : 
    app = create_app()
    app.run(debug=True)

flask_app/views/index_view.py
from flask import Blueprint
from flask import render_template

bp = Blueprint('main', __name__, url_prefix='/')

@bp.route('/')
def index():
    return render_template('index.html')

flask_app/views/predict_view.py
#### views.py
from flask import Blueprint, render_template, url_for, request
from werkzeug.utils import redirect
from flask_app.forms import ProductForm
from flask_app.models import Search,Product
from flask_app import db

bp = Blueprint("test", __name__, url_prefix="/pred")

@bp.route("/pred", methods=["GET", "POST"])
def Search_Product():
    form = ProductForm()
    if request.method == "POST" and form.validate_on_submit():
        # 클라이언트가 검색한 상품명
        search_product = form.product_name.data
        search = "%{}%".format(search_product)
        
        # 크롤링한 상품명 중, search가 포함된 모든 상품명을 리스트로 반환.
        products = Product.query.filter(Product.product_name.like(search)).all()
        print(products)
        # Search 테이블의 새로운 객체
        new_search = Search(search_name=search_product)
        db.session.add(new_search)
        db.session.commit()
        return render_template('products.html', form=form, products=products)
    else:
        form = ProductForm()

    return render_template('products.html', form=form, products=None)

flask_app/templates/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Go Vegan!</title> 
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="static/assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.15.4/js/all.js" crossorigin="anonymous"></script>
        <!-- Simple line icons-->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.5.5/css/simple-line-icons.min.css" rel="stylesheet" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{{url_for('static', filename='css/styles.css')}}" rel="stylesheet" />
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <a class="menu-toggle rounded" href="#"><i class="fas fa-bars"></i></a>
        <nav id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li class="sidebar-brand"><a href="#page-top">Go Vegan!</a></li>
                <li class="sidebar-nav-item"><a href="#page-top">Home</a></li>
                <li class="sidebar-nav-item"><a href="#about">Search</a></li>
                <li class="sidebar-nav-item"><a href="#portfolio">About</a></li>
                <li class="sidebar-nav-item"><a href="#contact">Contact</a></li>
            </ul>
        </nav>
        <!-- Header-->
        <header class="masthead d-flex align-items-center">
            <div class="container px-4 px-lg-5 text-center">
                <h1 class="mb-1">GO VEGAN!</h1>
                <h3 class="mb-5"><em>Go vegan, Protect the Environment!</em></h3>
                <a class="btn btn-primary btn-xl" href="#about">Find Out More</a>
            </div>
        </header>
        <!-- About-->
        <section class="content-section bg-light" id="about">
            <div class="container px-4 px-lg-5 text-center">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-lg-10">
                        <h2>지속 가능한 환경을 위한 비거니즘과 그린슈머</h2>
                        <p class="lead mb-5">
                            비건 상품들을 알아보자!
                        </p>
                        <form class="needs-validation" nvaate method="POST", action="{{url_for('test.Search_Product')}}"><input type="submit" , value='What are vegan products?'>
                        <!-- <a class="btn btn-dark btn-xl" href="http://127.0.0.1:5000/pred/pred">What are vegan products?</a> -->
                    </div>
                </div>
            </div>
        </section>
  
        <!-- Portfolio-->
        <section class="content-section" id="portfolio">
            <div class="container px-4 px-lg-5">
                <div class="content-section-heading text-center">
                    <h3 class="text-secondary mb-0">About</h3>
                    <h2 class="mb-5">Recent Information</h2>
                </div>
                <div class="row gx-0">
                    <div class="col-lg-6">
                        <a class="portfolio-item" href="https://content.v.kakao.com/v/5f5f0bcc5803646c20678513">
                            <div class="caption">
                                <div class="caption-content">
                                    <div class="h2">Vegan Fashion</div>
                                    <p class="mb-0">기존의 먹는 채식주의를 뜻하는 비건의 의미를 '패션'까지 확장시킨 개념으로,환경을 생각해서 동물성 소재를 사용하지 않는 패션!</p>
                                </div>
                            </div>
                            <img class="img-fluid" src="{{url_for('static', filename='assets/img/vegan-1.jpg')}}" alt="..." />
                        </a>
                    </div>
                    <div class="col-lg-6">
                        <a class="portfolio-item" href="https://m.post.naver.com/viewer/postView.nhn?volumeNo=30815370&memberNo=1912446">
                            <div class="caption">
                                <div class="caption-content">
                                    <div class="h2">Veganism & Greensumer</div>
                                    <p class="mb-0">지속 가능한 환경을 위한 비거니즘과 그린슈머</p>
                                </div>
                            </div>
                            <img class="img-fluid" src="{{url_for('static', filename='assets/img/vegan-2.jpg')}}" alt="..." />
                        </a>
                    </div>
                    <div class="col-lg-6">
                        <a class="portfolio-item" href="https://www.dgupress.com/news/articleView.html?idxno=40291">
                            <div class="caption">
                                <div class="caption-content">
                                    <div class="h2">Veganomics</div>
                                    <p class="mb-0">채식주의자(vegan)에 경제(economics)를 합친 비거노믹스는 동물성 재료를 쓰지 않고 물건을 만드는 전반적인 산업!</p>
                                </div>
                            </div>
                            <img class="img-fluid" src="{{url_for('static', filename='assets/img/vegan-3.jpg')}}" alt="..." />
                        </a>
                    </div>
                    <div class="col-lg-6">
                        <a class="portfolio-item" href="https://www.catch.co.kr/News/RecruitNews/295217">
                            <div class="caption">
                                <div class="caption-content">
                                    <div class="h2">비건생산 기업</div>
                                    <p class="mb-0">한국채식연합등에 따르면 육식이 몸에 맞지 않거나 종교적인 이유 이외에도 착한소비를 위해 비건을 선택하는 사람이 늘고 있다.</p>
                                </div>
                            </div>
                            <img class="img-fluid" src="{{url_for('static', filename='assets/img/vegan-4.jpg')}}" alt="..." />
                        </a>
                    </div>
                </div>
            </div>
        </section>
        <!-- Footer-->
        <footer class="footer text-center">
            <div class="container px-4 px-lg-5">
                <ul class="list-inline mb-5">
                    <li class="list-inline-item">
                        <a class="social-link rounded-circle text-white mr-3" href="https://ko-kr.facebook.com/"><i class="icon-social-facebook"></i></a>
                    </li>
                    <li class="list-inline-item">
                        <a class="social-link rounded-circle text-white mr-3" href="https://twitter.com/home"><i class="icon-social-twitter"></i></a>
                    </li>
                    <li class="list-inline-item">
                        <a class="social-link rounded-circle text-white" href="https://github.com/ssu-jeong"><i class="icon-social-github"></i></a>
                    </li>
                </ul>
                <p class="text-muted small mb-0">Copyright &copy; Go-Vegan! 2021</p>
            </div>
        </footer>
        <!-- Scroll to Top Button-->
        <a class="scroll-to-top rounded" href="#page-top"><i class="fas fa-angle-up"></i></a>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{{url_for('static', filename='scripts.js')}}"></script>
        
    </body>
</html>

flask_app/templates/products.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Go Vegan!</title> 
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="static/assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.15.4/js/all.js" crossorigin="anonymous"></script>
        <!-- Simple line icons-->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.5.5/css/simple-line-icons.min.css" rel="stylesheet" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link rel="stylesheet" href="{{url_for('static', filename='css/styles.css')}}">
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <a class="menu-toggle rounded" href="#"><i class="fas fa-bars"></i></a>
        <nav id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li class="sidebar-brand"><a href="#page-top">Go Vegan!</a></li>
                <li class="sidebar-nav-item"><a href="#page-top">Home</a></li>
                <li class="sidebar-nav-item"><a href="#about">Search</a></li>
                <li class="sidebar-nav-item"><a href="#portfolio">About</a></li>
                <li class="sidebar-nav-item"><a href="#contact">Contact</a></li>
            </ul>
        </nav>
        <!-- Header-->
        <header class="masthead d-flex align-items-center">
            <div class="container px-4 px-lg-5 text-center">
                <h1 class="mb-1">GO VEGAN!</h1>
                <h3 class="mb-5"><em>What are vegan products?</h3>
                
                <title>상품명입력</title>
                <form method="post" class="post-form my-3">
                    {{ form.csrf_token }}
                    <tr>
                        <td>
                        {{ form.product_name.label }}
                        {{ form.product_name() }}
                        </td>
                    </tr>
                    <button type="submit" class="btn btn-primary">검색</button>
                </form>
                <div class="container px-4 px-lg-5 text-center" style="background-color: white;">
                    {% if products %}
                        {% for product in products %}
                            <h5>상품명: {{product.clean_name}}</h5>
                            <img src="{{product.image_url}}">
                        {% endfor %}
                    {% else %}
                        <h5>아직 비건제품이 제공되지 않네요:-(</h5>                   
                    {% endif %}
                </div>
                <br><br>
                <a class="btn btn-dark btn-xl" href='/'>Go back to home page</a>
            </div>
        </header>
        <br><br><br><br>
        <!-- Footer-->
        <footer class="footer text-center">
            <div class="container px-4 px-lg-5">
                <ul class="list-inline mb-5">
                    <li class="list-inline-item">
                        <a class="social-link rounded-circle text-white mr-3" href="https://ko-kr.facebook.com/"><i class="icon-social-facebook"></i></a>
                    </li>
                    <li class="list-inline-item">
                        <a class="social-link rounded-circle text-white mr-3" href="https://twitter.com/home"><i class="icon-social-twitter"></i></a>
                    </li>
                    <li class="list-inline-item">
                        <a class="social-link rounded-circle text-white" href="https://github.com/ssu-jeong"><i class="icon-social-github"></i></a>
                    </li>
                </ul>
                <p class="text-muted small mb-0">Copyright &copy; Go-Vegan! 2021</p>
            </div>
        </footer>
        <!-- Scroll to Top Button-->
        <a class="scroll-to-top rounded" href="#page-top"><i class="fas fa-angle-up"></i></a>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{{url_for('static', filename='scripts.js')}}"></script>
    </body>
</html>